from __future__ import annotations

import argparse
import json
import logging
import sys
from pathlib import Path

from .config import load_settings
from .gemini import build_dry_run_summary, summarize_episode
from .models import Video
from .output import (
    save_dry_run_summary,
    save_summary,
    save_transcript,
    save_video_metadata,
    summary_path,
    transcript_path,
)
from .podcast_feed import PodcastFeedError, fetch_latest_podcast_episodes
from .state import load_processed_video_ids, mark_video_processed
from .telegram import send_telegram_message
from .transcript import TranscriptUnavailableError, fetch_transcript_text
from .whisper_transcript import WhisperTranscriptError, transcribe_audio_url
from .youtube_feed import (
    YouTubeApiError,
    YouTubeFeedError,
    fetch_latest_videos,
    fetch_latest_videos_from_api,
)

logger = logging.getLogger(__name__)


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")

    logging.basicConfig(
        level=logging.INFO,
        format="%(levelname)s %(message)s",
        stream=sys.stdout,
        force=True,
    )

    args = parse_args(argv)
    settings = load_settings()

    try:
        logger.info("Starting podcast stock tracker.")
        if args.summarize_transcript_file:
            _summarize_transcript_file(Path(args.summarize_transcript_file), args, settings)
            return 0

        if args.send_summary_file:
            _send_summary_file(Path(args.send_summary_file), settings)
            return 0

        videos = _select_videos(args, settings)
        logger.info("Selected %s video(s) to process.", len(videos))
        if not videos:
            logger.info("No new videos to process.")
            return 0

        for video in videos:
            processed = _process_video(video, args, settings)
            if processed and not args.dry_run:
                mark_video_processed(settings.state_file, video.video_id)

        return 0
    except Exception:
        logger.exception("Run failed.")
        return 1


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Track mentioned stock symbols from a YouTube podcast transcript."
    )
    parser.add_argument(
        "--video-id",
        help="Process one YouTube video ID directly instead of reading the RSS feed.",
    )
    parser.add_argument(
        "--title",
        default="Manual video",
        help="Title used with --video-id.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Fetch transcript and print output without calling Gemini or Telegram.",
    )
    parser.add_argument(
        "--ignore-state",
        action="store_true",
        help="Process matching videos even if they already exist in the state file.",
    )
    parser.add_argument(
        "--send-summary-file",
        help="Send a saved Markdown summary file to Telegram without processing a video.",
    )
    parser.add_argument(
        "--summarize-transcript-file",
        help="Summarize a saved transcript file with Gemini without fetching YouTube data.",
    )
    parser.add_argument(
        "--send-after-summary",
        action="store_true",
        help="Send the summary generated by --summarize-transcript-file to Telegram.",
    )
    return parser.parse_args(argv)


def _summarize_transcript_file(
    transcript_path: Path,
    args: argparse.Namespace,
    settings: object,
) -> None:
    if not transcript_path.exists():
        raise FileNotFoundError(f"Transcript file not found: {transcript_path}")
    if not transcript_path.is_file():
        raise ValueError(f"Transcript path is not a file: {transcript_path}")

    transcript_text = transcript_path.read_text(encoding="utf-8").strip()
    if not transcript_text:
        raise ValueError(f"Transcript file is empty: {transcript_path}")

    video = _video_from_transcript_path(transcript_path, args)
    summary = summarize_episode(
        api_key=settings.gemini_api_key,
        model=settings.gemini_model,
        video=video,
        transcript_text=transcript_text,
    )

    print(summary)
    if settings.save_outputs:
        summary_path = save_summary(settings.output_dir, video, summary)
        logger.info("Saved summary: %s", summary_path)

    if args.send_after_summary:
        send_telegram_message(
            bot_token=settings.telegram_bot_token,
            chat_id=settings.telegram_chat_id,
            text=summary,
        )
        logger.info("Generated summary sent to Telegram.")


def _video_from_transcript_path(transcript_path: Path, args: argparse.Namespace) -> Video:
    metadata_path = transcript_path.parent / "metadata.json"
    metadata: dict[str, str] = {}
    if metadata_path.exists():
        raw_metadata = json.loads(metadata_path.read_text(encoding="utf-8"))
        metadata = {
            key: str(value)
            for key, value in raw_metadata.items()
            if value is not None
        }

    video_id = args.video_id or metadata.get("video_id") or transcript_path.parent.name.rsplit("_", 1)[-1]
    title = args.title if args.title != "Manual video" else metadata.get("title", args.title)
    url = metadata.get("url") or f"https://www.youtube.com/watch?v={video_id}"

    return Video(
        video_id=video_id,
        title=title,
        url=url,
        published=metadata.get("published", ""),
    )


def _send_summary_file(summary_path: Path, settings: object) -> None:
    if not summary_path.exists():
        raise FileNotFoundError(f"Summary file not found: {summary_path}")
    if not summary_path.is_file():
        raise ValueError(f"Summary path is not a file: {summary_path}")

    summary = summary_path.read_text(encoding="utf-8").strip()
    if not summary:
        raise ValueError(f"Summary file is empty: {summary_path}")

    send_telegram_message(
        bot_token=settings.telegram_bot_token,
        chat_id=settings.telegram_chat_id,
        text=summary,
    )
    logger.info("Summary file sent: %s", summary_path)


def _select_videos(args: argparse.Namespace, settings: object) -> list[Video]:
    if args.video_id:
        logger.info("Using manually provided video ID: %s", args.video_id)
        return [
            Video(
                video_id=args.video_id,
                title=args.title,
                url=f"https://www.youtube.com/watch?v={args.video_id}",
                published="",
            )
        ]

    if settings.podcast_rss_url:
        logger.info("Fetching latest episodes from podcast RSS feed.")
        try:
            videos = fetch_latest_podcast_episodes(
                settings.podcast_rss_url,
                max_results=min(max(settings.max_videos_per_run * 5, 5), 50),
            )
        except PodcastFeedError as exc:
            logger.warning("Podcast RSS feed is temporarily unavailable: %s", exc)
        else:
            logger.info("Fetched %s episode(s) from podcast RSS feed.", len(videos))
            processed_ids = set() if args.ignore_state else load_processed_video_ids(settings.state_file)
            logger.info("Loaded %s processed episode ID(s).", len(processed_ids))
            new_videos = [video for video in videos if video.video_id not in processed_ids]
            return new_videos[: settings.max_videos_per_run]

    if settings.youtube_api_key:
        logger.info("Fetching latest videos with YouTube Data API.")
        try:
            videos = fetch_latest_videos_from_api(
                channel_id=settings.youtube_channel_id,
                api_key=settings.youtube_api_key,
                max_results=min(max(settings.max_videos_per_run * 5, 5), 50),
            )
        except YouTubeApiError as exc:
            logger.warning("YouTube Data API is temporarily unavailable: %s", exc)
        else:
            logger.info("Fetched %s video(s) with YouTube Data API.", len(videos))
            processed_ids = set() if args.ignore_state else load_processed_video_ids(settings.state_file)
            logger.info("Loaded %s processed video ID(s).", len(processed_ids))
            new_videos = [video for video in videos if video.video_id not in processed_ids]
            return new_videos[: settings.max_videos_per_run]

    logger.info("Fetching YouTube RSS feed for channel: %s", settings.youtube_channel_id)
    try:
        videos = fetch_latest_videos(settings.youtube_channel_id)
    except YouTubeFeedError as exc:
        logger.warning("YouTube RSS feed is temporarily unavailable: %s", exc)
        return []

    logger.info("Fetched %s video(s) from YouTube RSS feed.", len(videos))
    processed_ids = set() if args.ignore_state else load_processed_video_ids(settings.state_file)
    logger.info("Loaded %s processed video ID(s).", len(processed_ids))
    new_videos = [video for video in videos if video.video_id not in processed_ids]
    return new_videos[: settings.max_videos_per_run]


def _process_video(video: Video, args: argparse.Namespace, settings: object) -> bool:
    logger.info("Processing video: %s (%s)", video.title, video.video_id)

    saved_transcript_path = transcript_path(settings.output_dir, video)
    transcript_generated = False
    if settings.save_outputs and saved_transcript_path.exists():
        transcript_text = saved_transcript_path.read_text(encoding="utf-8").strip()
        if transcript_text:
            logger.info("Using saved transcript: %s", saved_transcript_path)
        else:
            logger.warning("Saved transcript is empty; regenerating: %s", saved_transcript_path)
            transcript_text = ""
    else:
        transcript_text = ""

    if not transcript_text:
        try:
            if video.audio_url:
                if not settings.enable_whisper_fallback:
                    logger.warning("Podcast episode requires Whisper, but ENABLE_WHISPER_FALLBACK is false.")
                    return False

                transcript_text = transcribe_audio_url(
                    video.audio_url,
                    model_name=settings.whisper_model,
                    language=settings.whisper_language,
                )
            else:
                transcript_text = fetch_transcript_text(
                    video.video_id,
                    enable_whisper_fallback=settings.enable_whisper_fallback,
                    whisper_model=settings.whisper_model,
                    whisper_language=settings.whisper_language,
                )
            transcript_generated = True
        except TranscriptUnavailableError as exc:
            logger.warning("Transcript unavailable for %s: %s", video.video_id, exc)
            return False
        except WhisperTranscriptError as exc:
            logger.warning("Podcast audio transcription unavailable for %s: %s", video.video_id, exc)
            return False

    metadata_path = saved_transcript_path.parent / "metadata.json"
    if settings.save_outputs and (transcript_generated or not metadata_path.exists()):
        metadata_path = save_video_metadata(settings.output_dir, video)
        saved_transcript_path = save_transcript(settings.output_dir, video, transcript_text)
        logger.info("Saved metadata: %s", metadata_path)
        logger.info("Saved transcript: %s", saved_transcript_path)

    if args.dry_run:
        summary = build_dry_run_summary(video, transcript_text)
        if settings.save_outputs:
            summary_path = save_dry_run_summary(settings.output_dir, video, summary)
            logger.info("Saved dry-run summary: %s", summary_path)
        print(summary)
        return False

    saved_summary_path = summary_path(settings.output_dir, video)
    if settings.save_outputs and saved_summary_path.exists():
        summary = saved_summary_path.read_text(encoding="utf-8").strip()
        if summary:
            logger.info("Using saved summary: %s", saved_summary_path)
        else:
            logger.warning("Saved summary is empty; regenerating: %s", saved_summary_path)
            summary = ""
    else:
        summary = ""

    if not summary:
        summary = summarize_episode(
            api_key=settings.gemini_api_key,
            model=settings.gemini_model,
            video=video,
            transcript_text=transcript_text,
        )
        if settings.save_outputs:
            saved_summary_path = save_summary(settings.output_dir, video, summary)
            logger.info("Saved summary: %s", saved_summary_path)

    send_telegram_message(
        bot_token=settings.telegram_bot_token,
        chat_id=settings.telegram_chat_id,
        text=summary,
    )
    logger.info("Video processed and sent: %s", video.video_id)
    return True


if __name__ == "__main__":
    sys.exit(main())
